"""Output formatters."""
from typing import Dict, Any
import json

def format_bug_report(context: Dict[str, Any]) -> Dict[str, Any]:
    """Format bug report."""
    return {
        "title": "Bug Report: TypeError in get_user_orders",
        "summary": extract_summary(context.get("root_cause_analysis", "")),
        "root_cause": context.get("root_cause_analysis", ""),
        "reproduction_steps": context.get("reproduction_info", ""),
        "impact": extract_impact(context.get("root_cause_analysis", "")),
        "severity": "high",
        "affected_files": context.get("analyzed_files", []),
    }

def format_pull_request(context: Dict[str, Any]) -> Dict[str, Any]:
    """Format pull request."""
    return {
        "title": "Fix: Handle None return from get_orders_by_user",
        "description": generate_pr_description(context),
        "files_changed": context.get("analyzed_files", []),
        "tests_added": context.get("test_code", ""),
        "review_status": extract_review_status(context.get("review_result", "")),
    }

def extract_summary(root_cause: str) -> str:
    """Extract summary from root cause analysis."""
    try:
        data = json.loads(root_cause)
        return data.get("root_cause", root_cause[:200])
    except:
        return root_cause[:200]

def extract_impact(root_cause: str) -> str:
    """Extract impact from root cause analysis."""
    try:
        data = json.loads(root_cause)
        return data.get("impact", "Unknown impact")
    except:
        return "Unknown impact"

def extract_review_status(review: str) -> str:
    """Extract review status."""
    try:
        data = json.loads(review)
        return data.get("approval_status", "pending")
    except:
        return "pending"

def generate_pr_description(context: Dict[str, Any]) -> str:
    """Generate PR description."""
    return f"""##  Bug Fix

**Root Cause:**
{extract_summary(context.get('root_cause_analysis', ''))}

**Fix:**
{extract_summary(context.get('fix_proposal', ''))}

**Testing:**
{extract_summary(context.get('test_code', ''))}

**Review:**
{extract_review_status(context.get('review_result', ''))}

Generated by MYTHEOS 🤖
"""